/*
 * transmitsms_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package keywords_pkg

import "transmitsms_lib/configuration_pkg"

/*
 * Interface for the KEYWORDS_IMPL
 */
type KEYWORDS interface {
    GetKeywords (string, *string, *string, *string) (interface{}, error)

    AddKeyword (string, string, string, *string, *string, *string, *string, *string, *string, *string, *string) (interface{}, error)

    EditKeyword (string, string, string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (interface{}, error)
}

/*
 * Factory for the KEYWORDS interaface returning KEYWORDS_IMPL
 */
func NewKEYWORDS(config configuration_pkg.CONFIGURATION) *KEYWORDS_IMPL {
    client := new(KEYWORDS_IMPL)
    client.config = config
    return client
}