/*
 * transmitsms_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package emailsms_pkg

import "transmitsms_lib/configuration_pkg"

/*
 * Interface for the EMAILSMS_IMPL
 */
type EMAILSMS interface {
    AddEmail (string, string, string, *string) (interface{}, error)

    DeleteEmail (string, string) (interface{}, error)
}

/*
 * Factory for the EMAILSMS interaface returning EMAILSMS_IMPL
 */
func NewEMAILSMS(config configuration_pkg.CONFIGURATION) *EMAILSMS_IMPL {
    client := new(EMAILSMS_IMPL)
    client.config = config
    return client
}