/*
 * transmitsms_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package configuration_pkg


/** The base Uri for API calls */
const BASEURI string = "https://api.transmitsms.com"



type CONFIGURATION_IMPL struct {
    /** API Key */
    /** Replace the value of Username with an appropriate value */
    username string
    /** Secret */
    /** Replace the value of Password with an appropriate value */
    password string
}

/*
 * Getter function returning username
 */
func (me *CONFIGURATION_IMPL) Username() string{
    return me.username
}

/*
 * Setter function setting up username
 */
func (me *CONFIGURATION_IMPL) SetUsername(username string) {
    me.username = username
}

/*
 * Getter function returning password
 */
func (me *CONFIGURATION_IMPL) Password() string{
    return me.password
}

/*
 * Setter function setting up password
 */
func (me *CONFIGURATION_IMPL) SetPassword(password string) {
    me.password = password
}

