/*
 * transmitsms_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package TransmitSMSClient

import(
	"transmitsms_lib/configuration_pkg"
	"transmitsms_lib/sms_pkg"
	"transmitsms_lib/numbers_pkg"
	"transmitsms_lib/emailsms_pkg"
	"transmitsms_lib/resellers_pkg"
	"transmitsms_lib/account_pkg"
	"transmitsms_lib/keywords_pkg"
	"transmitsms_lib/lists_pkg"
)


/*
 * Interface for the TRANSMITSMS_IMPL
 */
type TRANSMITSMS interface {
    SMS()                   sms_pkg.SMS
    Numbers()               numbers_pkg.NUMBERS
    EmailSMS()              emailsms_pkg.EMAILSMS
    Resellers()             resellers_pkg.RESELLERS
    Account()               account_pkg.ACCOUNT
    Keywords()              keywords_pkg.KEYWORDS
    Lists()                 lists_pkg.LISTS
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the TRANSMITSMS interface returning TRANSMITSMS_IMPL
 */
func NewTRANSMITSMS(username string, password string) TRANSMITSMS {
    transmitSMSClient := new(TRANSMITSMS_IMPL)
    transmitSMSClient.config = configuration_pkg.NewCONFIGURATION()

    transmitSMSClient.config.SetUsername(username)
    transmitSMSClient.config.SetPassword(password)

    return transmitSMSClient
}
