/*
 * transmitsms_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package resellers_pkg

import "transmitsms_lib/configuration_pkg"

/*
 * Interface for the RESELLERS_IMPL
 */
type RESELLERS interface {
    GetTransaction (string, string) (interface{}, error)

    EditClient (string, string, *string, *string, *string, *string, *string, *string, *string, *string) (interface{}, error)

    GetTransactions (string, string, *string, *string, *string, *string) (interface{}, error)

    GetClient (string, string) (interface{}, error)

    GetClients (string, *string, *string) (interface{}, error)

    AddClient (string, string, string, string, string, *string, *string, *string, *string, *string) (interface{}, error)
}

/*
 * Factory for the RESELLERS interaface returning RESELLERS_IMPL
 */
func NewRESELLERS(config configuration_pkg.CONFIGURATION) *RESELLERS_IMPL {
    client := new(RESELLERS_IMPL)
    client.config = config
    return client
}