/*
 * transmitsms_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package numbers_pkg

import "transmitsms_lib/configuration_pkg"

/*
 * Interface for the NUMBERS_IMPL
 */
type NUMBERS interface {
    LeaseNumber (string, string) (interface{}, error)

    EditNumberOptions (string, string, *string, *string, *string, *string, *string, *string) (interface{}, error)

    GetNumbers (string, string, *string, *string) (interface{}, error)

    GetNumber (string, string) (interface{}, error)
}

/*
 * Factory for the NUMBERS interaface returning NUMBERS_IMPL
 */
func NewNUMBERS(config configuration_pkg.CONFIGURATION) *NUMBERS_IMPL {
    client := new(NUMBERS_IMPL)
    client.config = config
    return client
}